package bracket

object MensTeams {

    val houston = Team(name = "Houston", powerRating = 93.2)
    val texas = Team(name = "Texas", powerRating = 90.1)
    val xavier = Team(name = "Xavier", powerRating = 84.4)
    val indiana = Team(name = "Indiana", powerRating = 85.8)
    val miami = Team(name = "Miami", powerRating = 83.6)
    val iowaState = Team(name = "Iowa State", powerRating = 84.5)
    val texasAM = Team(name = "Texas A&M", powerRating = 85.1)
    val iowa = Team(name = "Iowa", powerRating = 84.4)
    val auburn = Team(name = "Auburn", powerRating = 84.9)
    val pennState = Team(name = "Penn State", powerRating = 82.8)
    val pitt = Team(name = "Pitt", powerRating = 79.7)
    val drake = Team(name = "Drake", powerRating = 81.2)
    val kentState = Team(name = "Kent State", powerRating = 79.4)
    val kennState = Team(name = "Kenn State", powerRating = 73.3)
    val colgate = Team(name = "Colgate", powerRating = 76.2)
    val nKentucky = Team(name = "N. Kentucky", powerRating = 72.9)

    val kansas = Team(name = "Kansas", powerRating = 89.6)
    val ucla = Team(name = "UCLA", powerRating = 88.3)
    val gonzaga = Team(name = "Gonzaga", powerRating = 89.9)
    val uconn = Team(name = "UConn", powerRating = 89.2)
    val stMarys = Team(name = "St. Mary's", powerRating = 85.9)
    val tcu = Team(name = "TCU", powerRating = 85.4)
    val northwestern = Team(name = "N'western", powerRating = 82.2)
    val arkansas = Team(name = "Arkansas", powerRating = 85.1)
    val illinois = Team(name = "Illinois", powerRating = 84.5)
    val boiseSt = Team(name = "Boise St", powerRating = 82.6)
    val arizonaSt = Team(name = "Arizona St", powerRating = 80.3)
    val nevada = Team(name = "Nevada", powerRating = 79.6)
    val vcu = Team(name = "VCU", powerRating = 81.7)
    val iona = Team(name = "Iona", powerRating = 79.6)
    val grCanyon = Team(name = "Gr. Canyon", powerRating = 75.9)
    val uncAsh = Team(name = "UNC-Ash.", powerRating = 73.0)
    val howard = Team(name = "Howard", powerRating = 69.3)

    val purdue = Team(name = "Purdue", powerRating = 89.5)
    val marquette = Team(name = "Marquette", powerRating = 87.6)
    val kansasSt = Team(name = "Kansas St", powerRating = 84.5)
    val tennessee = Team(name = "Tennessee", powerRating = 86.9)
    val duke = Team(name = "Duke", powerRating = 87.1)
    val kentucky = Team(name = "Kentucky", powerRating = 86.0)
    val michiganSt = Team(name = "Michigan St", powerRating = 83.8)
    val memphis = Team(name = "Memphis", powerRating = 84.9)
    val fau = Team(name = "FAU", powerRating = 82.6)
    val usc = Team(name = "USC", powerRating = 83.0)
    val providence = Team(name = "Providence", powerRating = 82.8)
    val oralRoberts = Team(name = "Oral Roberts", powerRating = 79.2)
    val uLaLa = Team(name = "ULaLa", powerRating = 76.3)
    val montanaSt = Team(name = "Montana St", powerRating = 75.3)
    val vermont = Team(name = "Vermont", powerRating = 76.3)
    val fDickinson = Team(name = "F. Dickinson", powerRating = 64.4)
    val txSo = Team(name = "TXSO", powerRating = 66.6)

    val alabama = Team(name = "Alabama", powerRating = 92.6)
    val arizona = Team(name = "Arizona", powerRating = 89.0)
    val baylor = Team(name = "Baylor", powerRating = 87.1)
    val virginia = Team(name = "Virginia", powerRating = 83.8)
    val sdsu = Team(name = "SDSU", powerRating = 86.0)
    val creighton = Team(name = "Creighton", powerRating = 87.6)
    val missouri = Team(name = "Missouri", powerRating = 81.4)
    val maryland = Team(name = "Maryland", powerRating = 84.5)
    val wvu = Team(name = "WVU", powerRating = 84.2)
    val utahSt = Team(name = "Utah St", powerRating = 83.5)
    val ncSt = Team(name = "NC St", powerRating = 81.4)
    val charleston = Team(name = "Charleston", powerRating = 79.8)
    val furman = Team(name = "Furman", powerRating = 78.2)
    val ucsb = Team(name = "UCSB", powerRating = 75.5)
    val princeton = Team(name = "Princeton", powerRating = 75.4)
    val tamuCC = Team(name = "TAMU CC", powerRating = 70.6)
}

object MensTeams2024 {
    val connecticut = Team(name = "Connecticut", powerRating = 95.6)
    val houston = Team(name = "Houston", powerRating = 92.1)
    val purdue = Team(name = "Purdue", powerRating = 93.5)
    val arizona = Team(name = "Arizona", powerRating = 91.6)
    val iowaSt = Team(name = "Iowa St", powerRating = 90.9)
    val auburn = Team(name = "Auburn", powerRating = 90.6)
    val tennessee = Team(name = "Tennessee", powerRating = 90.6)
    val northCarolina = Team(name = "North Carolina", powerRating = 90.2)
    val duke = Team(name = "Duke", powerRating = 89.4)
    val creighton = Team(name = "Creighton", powerRating = 89.6)
    val marquette = Team(name = "Marquette", powerRating = 85.3)
    val illinois = Team(name = "Illinois", powerRating = 89.8)
    val baylor = Team(name = "Baylor", powerRating = 87.9)
    val gonzaga = Team(name = "Gonzaga", powerRating = 88.0)
    val alabama = Team(name = "Alabama", powerRating = 87.8)
    val kansas = Team(name = "Kansas", powerRating = 85.5)
    val kentucky = Team(name = "Kentucky", powerRating = 88.3)
    val michSt = Team(name = "Michigan St", powerRating = 86.9)
    val saintMarys = Team(name = "Saint Mary's", powerRating = 84.7)
    val wisconsin = Team(name = "Wisconsin", powerRating = 86.6)
    val texas = Team(name = "Texas", powerRating = 86.6)
    val byu = Team(name = "BYU", powerRating = 86.4)
    val florida = Team(name = "Florida", powerRating = 84.2)
    val sanDiegoSt = Team(name = "San Diego St", powerRating = 85.6)
    val texasTech = Team(name = "Texas Tech", powerRating = 83.3)
    val missSt = Team(name = "Mississippi St", powerRating = 85.5)
    val tcu = Team(name = "TCU", powerRating = 85.0)
    val fau = Team(name = "FAU", powerRating = 84.8)
    val colorado = Team(name = "Colorado", powerRating = 84.8)
    val tamu = Team(name = "Texas A&M", powerRating = 85.0)
    val nebraska = Team(name = "Nebraska", powerRating = 84.2)
    val newMexico = Team(name = "New Mexico", powerRating = 84.2)
    val clemson = Team(name = "Clemson", powerRating = 83.8)
    val northwestern = Team(name = "Northwestern", powerRating = 80.7)
    val washSt = Team(name = "Wash St", powerRating = 83.4)
    val dayton = Team(name = "Dayton", powerRating = 83.1)
    val drake = Team(name = "Drake", powerRating = 82.9)
    val nevada = Team(name = "Nevada", powerRating = 82.3)
    val oregon = Team(name = "Oregon", powerRating = 82.5)
    val utahSt = Team(name = "Utah St", powerRating = 82.3)
    val ncState = Team(name = "NC State", powerRating = 81.9)
    val southCarolina = Team(name = "South Carolina", powerRating = 82.3)
    val coloradoSt = Team(name = "Colorado St", powerRating = 81.5)
    val grandCanyon = Team(name = "Grand Canyon", powerRating = 81.2)
    val jmu = Team(name = "JMU", powerRating = 81.2)
    val yale = Team(name = "Yale", powerRating = 79.7)
    val charleston = Team(name = "Charleston", powerRating = 79.5)
    val duquesne = Team(name = "Duquesne", powerRating = 79.0)
    val vermont = Team(name = "Vermont", powerRating = 78.6)
    val samford = Team(name = "Samford", powerRating = 78.6)
    val uab = Team(name = "UAB", powerRating = 78.5)
    val mcNeeseSt = Team(name = "McNeese St", powerRating = 78.3)
    val akron = Team(name = "Akron", powerRating = 76.8)
    val colgate = Team(name = "Colgate", powerRating = 76.2)
    val moreheadSt = Team(name = "Morehead St", powerRating = 75.9)
    val westernKY = Team(name = "Western KY", powerRating = 74.7)
    val southDakotaSt = Team(name = "South Dakota St", powerRating = 74.5)
    val oakland = Team(name = "Oakland", powerRating = 74.4)
    val longwood = Team(name = "Longwood", powerRating = 73.4)
    val longBeachSt = Team(name = "Long Beach St", powerRating = 72.7)
    val stPeters = Team(name = "St. Peter's", powerRating = 71.2)
    val stetson = Team(name = "Stetson", powerRating = 70.8)
    val grambling = Team(name = "Grambling", powerRating = 68.1)
    val wagner = Team(name = "Wagner", powerRating = 66.4)
}