package bracket

object MensTeams {

    val houston = Team(name = "Houston", powerRating = 93.2)
    val texas = Team(name = "Texas", powerRating = 90.1)
    val xavier = Team(name = "Xavier", powerRating = 84.4)
    val indiana = Team(name = "Indiana", powerRating = 85.8)
    val miami = Team(name = "Miami", powerRating = 83.6)
    val iowaState = Team(name = "Iowa State", powerRating = 84.5)
    val texasAM = Team(name = "Texas A&M", powerRating = 85.1)
    val iowa = Team(name = "Iowa", powerRating = 84.4)
    val auburn = Team(name = "Auburn", powerRating = 84.9)
    val pennState = Team(name = "Penn State", powerRating = 82.8)
    val pitt = Team(name = "Pitt", powerRating = 79.7)
    val drake = Team(name = "Drake", powerRating = 81.2)
    val kentState = Team(name = "Kent State", powerRating = 79.4)
    val kennState = Team(name = "Kenn State", powerRating = 73.3)
    val colgate = Team(name = "Colgate", powerRating = 76.2)
    val nKentucky = Team(name = "N. Kentucky", powerRating = 72.9)

    val kansas = Team(name = "Kansas", powerRating = 89.6)
    val ucla = Team(name = "UCLA", powerRating = 88.3)
    val gonzaga = Team(name = "Gonzaga", powerRating = 89.9)
    val uconn = Team(name = "UConn", powerRating = 89.2)
    val stMarys = Team(name = "St. Mary's", powerRating = 85.9)
    val tcu = Team(name = "TCU", powerRating = 85.4)
    val northwestern = Team(name = "N'western", powerRating = 82.2)
    val arkansas = Team(name = "Arkansas", powerRating = 85.1)
    val illinois = Team(name = "Illinois", powerRating = 84.5)
    val boiseSt = Team(name = "Boise St", powerRating = 82.6)
    val arizonaSt = Team(name = "Arizona St", powerRating = 80.3)
    val nevada = Team(name = "Nevada", powerRating = 79.6)
    val vcu = Team(name = "VCU", powerRating = 81.7)
    val iona = Team(name = "Iona", powerRating = 79.6)
    val grCanyon = Team(name = "Gr. Canyon", powerRating = 75.9)
    val uncAsh = Team(name = "UNC-Ash.", powerRating = 73.0)
    val howard = Team(name = "Howard", powerRating = 69.3)

    val purdue = Team(name = "Purdue", powerRating = 89.5)
    val marquette = Team(name = "Marquette", powerRating = 87.6)
    val kansasSt = Team(name = "Kansas St", powerRating = 84.5)
    val tennessee = Team(name = "Tennessee", powerRating = 86.9)
    val duke = Team(name = "Duke", powerRating = 87.1)
    val kentucky = Team(name = "Kentucky", powerRating = 86.0)
    val michiganSt = Team(name = "Michigan St", powerRating = 83.8)
    val memphis = Team(name = "Memphis", powerRating = 84.9)
    val fau = Team(name = "FAU", powerRating = 82.6)
    val usc = Team(name = "USC", powerRating = 83.0)
    val providence = Team(name = "Providence", powerRating = 82.8)
    val oralRoberts = Team(name = "Oral Roberts", powerRating = 79.2)
    val uLaLa = Team(name = "ULaLa", powerRating = 76.3)
    val montanaSt = Team(name = "Montana St", powerRating = 75.3)
    val vermont = Team(name = "Vermont", powerRating = 76.3)
    val fDickinson = Team(name = "F. Dickinson", powerRating = 64.4)
    val txSo = Team(name = "TXSO", powerRating = 66.6)

    val alabama = Team(name = "Alabama", powerRating = 92.6)
    val arizona = Team(name = "Arizona", powerRating = 89.0)
    val baylor = Team(name = "Baylor", powerRating = 87.1)
    val virginia = Team(name = "Virginia", powerRating = 83.8)
    val sdsu = Team(name = "SDSU", powerRating = 86.0)
    val creighton = Team(name = "Creighton", powerRating = 87.6)
    val missouri = Team(name = "Missouri", powerRating = 81.4)
    val maryland = Team(name = "Maryland", powerRating = 84.5)
    val wvu = Team(name = "WVU", powerRating = 84.2)
    val utahSt = Team(name = "Utah St", powerRating = 83.5)
    val ncSt = Team(name = "NC St", powerRating = 81.4)
    val charleston = Team(name = "Charleston", powerRating = 79.8)
    val furman = Team(name = "Furman", powerRating = 78.2)
    val ucsb = Team(name = "UCSB", powerRating = 75.5)
    val princeton = Team(name = "Princeton", powerRating = 75.4)
    val tamuCC = Team(name = "TAMU CC", powerRating = 70.6)
}